#!/bin/sh

mkdir /mnt/{proc,dev,sys,var/lib/pacman}
mount -o bind /dev /mnt/dev
mount -t sysfs none /mnt/sys
mount -t proc none /mnt/proc
pacman --noconfirm -r /mnt -S base btrfs-progs haveged vim-minimal
